import re

with open('C:\\Users\\Student\\Desktop\\summer-school\\generate_html.py', 'r') as f:
    content = f.read()

# Find CSS block boundaries
start = content.find('# --- BUILD CSS ---')
style_start = content.find("css = '''<style>", start)
style_end = content.find("</style>'''", style_start) + len("</style>'''")

# Build new CSS (no quotes inside string to avoid escaping issues)
parts = []
parts.append("@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&display=swap');")
parts.append('*{margin:0;padding:0;box-sizing:border-box}html{scroll-behavior:smooth}')
parts.append('body{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;background:#05050a;color:#c8c8d4;min-height:100vh;line-height:1.5;overflow-x:hidden}')
parts.append(':root{--bg:#05050a;--bg2:#0b0b14;--bg3:#10101c;--bg4:#161628;--fg:#c8c8d4;--fg2:#7777a0;--r1:#ff3b3b;--r2:#d32ce6;--r3:#8847ff;--r4:#4b69ff;--r5:#5e98d9;--r6:#b0b0c0;--r7:#ffd700}')
parts.append('body::before,body::after{content:;position:fixed;border-radius:50%;pointer-events:none;z-index:0;animation:orb 8s ease-in-out infinite}')
parts.append('body::before{width:500px;height:500px;background:radial-gradient(circle,rgba(235,75,75,.04) 0%,transparent 70%);top:-100px;left:-100px;animation-delay:0s}')
parts.append('body::after{width:600px;height:600px;background:radial-gradient(circle,rgba(136,71,255,.04) 0%,transparent 70%);bottom:-150px;right:-150px;animation-delay:3s}')
parts.append('@keyframes orb{0%,100%{transform:translate(0,0) scale(1)}33%{transform:translate(60px,-40px) scale(1.1)}66%{transform:translate(-30px,50px) scale(.9)}}')
parts.append('.nv{height:56px;background:rgba(5,5,10,.92);backdrop-filter:blur(20px);border-bottom:1px solid rgba(255,255,255,.04);position:sticky;top:0;z-index:100}')
parts.append('.nv>div{max-width:1280px;margin:0 auto;padding:0 24px;height:100%;display:flex;align-items:center;justify-content:space-between}')
parts.append('.nvl{display:flex;gap:10px;align-items:center}')
parts.append('.nvg{width:30px;height:30px;border-radius:8px;background:linear-gradient(135deg,var(--r1),#ff8c00);color:#fff;font-weight:900;font-size:12px;display:flex;align-items:center;justify-content:center;font-family:Orbitron,sans-serif}')
parts.append('.nvt{font-weight:800;color:#fff;font-size:15px;letter-spacing:-.3px;font-family:Orbitron,sans-serif}')
parts.append('.nvb{font-size:8px;color:var(--fg2);background:var(--bg3);border:1px solid rgba(255,255,255,.04);padding:2px 7px;border-radius:4px;font-weight:700;letter-spacing:.8px;text-transform:uppercase}')
parts.append('.nvr{display:none;gap:20px}@media(min-width:768px){.nvr{display:flex}}')
parts.append('.nvr a{color:var(--fg2);font-size:12px;text-decoration:none;transition:.2s;font-weight:600;letter-spacing:.3px;text-transform:uppercase}.nvr a:hover{color:#fff;text-shadow:0 0 20px rgba(255,255,255,.1)}')
parts.append('.hr{position:relative;overflow:hidden;padding:90px 0 50px;z-index:1}')
parts.append('.hr::before{content:;position:absolute;inset:0;background:radial-gradient(ellipse at 30% 40%,rgba(235,75,75,.08) 0%,transparent 60%),radial-gradient(ellipse at 70% 60%,rgba(136,71,255,.06) 0%,transparent 60%),radial-gradient(ellipse at 50% 80%,rgba(255,215,0,.04) 0%,transparent 50%);pointer-events:none;z-index:-1}')
parts.append('.hr::after{content:;position:absolute;top:0;left:0;width:100%;height:2px;background:linear-gradient(90deg,transparent,var(--r1),var(--r3),var(--r7),transparent);opacity:.5;animation:scan 3s linear infinite;pointer-events:none}')
parts.append('@keyframes scan{0%{transform:translateX(-100%)}100%{transform:translateX(100%)}}')
parts.append('.hri{max-width:1280px;margin:0 auto;padding:0 24px;position:relative;z-index:1}')
parts.append('.hrt{display:inline-flex;align-items:center;gap:8px;padding:5px 14px;border-radius:24px;background:rgba(235,75,75,.08);border:1px solid rgba(235,75,75,.15);font-size:10px;color:var(--r1);font-weight:700;letter-spacing:.5px;text-transform:uppercase;margin-bottom:16px;animation:fadeIn .6s}')
parts.append('.hrt span{width:6px;height:6px;border-radius:50%;background:var(--r1);animation:pulse 2s infinite}')
parts.append('@keyframes pulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.3;transform:scale(.7)}}')
parts.append('.hrh{font-size:42px;font-weight:900;color:#fff;line-height:1.05;margin-bottom:10px;letter-spacing:-.5px;font-family:Orbitron,sans-serif;text-transform:uppercase;animation:fadeIn .8s}')
parts.append('.hrh em{font-style:normal;background:linear-gradient(135deg,var(--r1),#ff8c00,var(--r7));-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;background-size:200% 200%;animation:grad 3s ease infinite}')
parts.append('@keyframes grad{0%,100%{background-position:0% 50%}50%{background-position:100% 50%}}')
parts.append('.hrp{color:var(--fg2);font-size:14px;max-width:460px;animation:fadeIn 1s}')
parts.append('@keyframes fadeIn{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}')
parts.append('.st{position:relative;z-index:1;background:var(--bg2);border-top:1px solid rgba(255,255,255,.02);border-bottom:1px solid rgba(255,255,255,.04)}')
parts.append('.st>div{max-width:1280px;margin:0 auto;padding:16px 24px;display:grid;grid-template-columns:repeat(4,1fr);gap:12px;text-align:center}')
parts.append('.stn{font-size:24px;font-weight:900;color:#fff;font-family:Orbitron,sans-serif}')
parts.append('.stl{font-size:10px;color:var(--fg2);text-transform:uppercase;letter-spacing:.5px;margin-top:2px}')
parts.append('.gs{position:relative;z-index:1;padding:16px 24px;background:var(--bg2);border-bottom:1px solid rgba(255,255,255,.04)}')
parts.append('.gs>div{max-width:1280px;margin:0 auto;position:relative}')
parts.append('.gs svg{position:absolute;left:14px;top:50%;transform:translateY(-50%);color:#555}')
parts.append('.gs input{width:100%;padding:12px 14px 12px 42px;border-radius:12px;border:1px solid rgba(255,255,255,.06);background:var(--bg3);color:#fff;font-size:14px;outline:none;transition:.25s;font-weight:400}')
parts.append('.gs input:focus{border-color:var(--r1);box-shadow:0 0 0 3px rgba(235,75,75,.08)}.gs input::placeholder{color:#555}')
parts.append('.gsc{text-align:center;padding:6px 0;font-size:11px;color:var(--fg2);font-weight:500}')
parts.append('.mn{max-width:1280px;margin:0 auto;padding:32px 24px 48px;position:relative;z-index:1}')
parts.append('.sc{margin-bottom:44px;animation:fadeIn .5s ease-out both}')
parts.append('.sc:nth-child(1){animation-delay:.1s}.sc:nth-child(2){animation-delay:.2s}.sc:nth-child(3){animation-delay:.3s}.sc:nth-child(4){animation-delay:.4s}.sc:nth-child(5){animation-delay:.5s}.sc:nth-child(6){animation-delay:.6s}')
parts.append('.sch{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px}')
parts.append('.sch-l{display:flex;align-items:center;gap:10px}')
parts.append('.sch-i{width:32px;height:32px;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:15px;animation:bounce 2s ease-in-out infinite}')
parts.append('@keyframes bounce{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}')
parts.append('.sch-t{font-size:18px;font-weight:800;color:#fff;letter-spacing:-.2px;font-family:Orbitron,sans-serif}')
parts.append('.sch-n{font-size:11px;color:var(--fg2);font-weight:600;background:var(--bg3);padding:2px 9px;border-radius:6px}')
parts.append('.sch-b{padding:8px 18px;border-radius:10px;background:transparent;border:1px solid rgba(235,75,75,.2);color:var(--r1);font-size:11px;font-weight:700;cursor:pointer;transition:.3s;text-transform:uppercase;letter-spacing:.3px}')
parts.append('.sch-b:hover{background:rgba(235,75,75,.08);border-color:var(--r1);box-shadow:0 0 20px rgba(235,75,75,.1)}')
parts.append('.gd{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}@media(min-width:500px){.gd{grid-template-columns:repeat(3,1fr)}}@media(min-width:700px){.gd{grid-template-columns:repeat(4,1fr)}}@media(min-width:900px){.gd{grid-template-columns:repeat(5,1fr)}}')
parts.append('.c{background:var(--bg2);border:1px solid rgba(255,255,255,.04);border-radius:12px;overflow:hidden;transition:all .35s cubic-bezier(.34,1.56,.64,1);cursor:pointer;position:relative;animation:cardIn .4s ease-out both}')
parts.append('.c:nth-child(1){animation-delay:.05s}.c:nth-child(2){animation-delay:.1s}.c:nth-child(3){animation-delay:.15s}.c:nth-child(4){animation-delay:.2s}.c:nth-child(5){animation-delay:.25s}.c:nth-child(6){animation-delay:.3s}.c:nth-child(7){animation-delay:.35s}.c:nth-child(8){animation-delay:.4s}.c:nth-child(9){animation-delay:.45s}.c:nth-child(10){animation-delay:.5s}')
parts.append('@keyframes cardIn{from{opacity:0;transform:translateY(20px) scale(.95)}to{opacity:1;transform:translateY(0) scale(1)}}')
parts.append('.c:hover{transform:translateY(-6px) scale(1.02);border-color:rgba(255,255,255,.08);box-shadow:0 16px 48px rgba(0,0,0,.4),0 0 30px rgba(235,75,75,.05)}.c.hide{display:none!important}')
parts.append('.ci{position:relative;aspect-ratio:4/3;background:linear-gradient(180deg,rgba(255,255,255,.015),transparent);display:flex;align-items:center;justify-content:center;padding:12px}')
parts.append('.ci img{width:100%;height:100%;object-fit:contain;transition:transform .5s cubic-bezier(.34,1.56,.64,1);filter:drop-shadow(0 4px 16px rgba(0,0,0,.5))}.c:hover .ci img{transform:scale(1.08) rotate(-1deg)}')
parts.append('.ch{position:absolute;inset:0;opacity:0;transition:.5s;background:linear-gradient(45deg,transparent 20%,rgba(255,255,255,.015) 40%,transparent 60%);pointer-events:none}.c:hover .ch{opacity:1}')
parts.append('.cb{padding:10px 12px 12px;position:relative}.cb::after{content:;position:absolute;top:0;left:12px;right:12px;height:1px;background:rgba(255,255,255,.04)}')
parts.append('.cb span{display:block;font-size:8px;font-weight:700;letter-spacing:.4px;text-transform:uppercase;margin-bottom:3px}.cb b{display:block;color:#fff;font-size:11px;font-weight:600;line-height:1.3}')
parts.append('.cb span:last-child{color:var(--fg2);font-size:10px;font-weight:400;text-transform:none;letter-spacing:0;margin-top:1px;margin-bottom:0}')
parts.append('.ov{position:fixed;inset:0;background:rgba(5,5,10,.95);z-index:200;overflow-y:auto;display:none;backdrop-filter:blur(4px)}.ov.s{display:block;animation:fadeIn .2s}')
parts.append('.ovt{position:sticky;top:0;z-index:10;background:rgba(11,11,20,.95);backdrop-filter:blur(20px);border-bottom:1px solid rgba(255,255,255,.04);display:flex;align-items:center;justify-content:space-between;padding:12px 24px}.ovtl{display:flex;align-items:center;gap:12px}')
parts.append('.ovb{padding:7px 14px;border-radius:8px;background:var(--bg3);border:1px solid rgba(255,255,255,.06);color:var(--fg2);font-size:12px;cursor:pointer;transition:.2s;display:flex;align-items:center;gap:5px;font-weight:500}.ovb:hover{color:#fff;border-color:var(--r1);background:rgba(235,75,75,.06)}')
parts.append('.ovbt{font-weight:700;color:#fff;font-size:15px;font-family:Orbitron,sans-serif}.ovbc{font-size:11px;color:var(--fg2)}')
parts.append('.ovf{background:var(--bg2);border-bottom:1px solid rgba(255,255,255,.04);padding:20px 24px;display:flex;flex-direction:column;gap:14px}')
parts.append('.ovf .ovfs,.ovf .ovfg,.ovf .ovff{max-width:640px;margin-left:auto;margin-right:auto;width:100%}')
parts.append('.ovfs{position:relative}.ovfs svg{position:absolute;left:14px;top:50%;transform:translateY(-50%);color:#555}')
parts.append('.ovfs input{width:100%;padding:11px 14px 11px 40px;border-radius:10px;border:1px solid rgba(255,255,255,.06);background:var(--bg3);color:#fff;font-size:14px;outline:none;transition:.2s}')
parts.append('.ovfs input:focus{border-color:var(--r1);box-shadow:0 0 0 3px rgba(235,75,75,.06)}.ovfs input::placeholder{color:#555}')
parts.append('.ovfg{display:flex;flex-direction:column;gap:8px}.ovfl{font-size:9px;font-weight:700;color:#666;text-transform:uppercase;letter-spacing:1px;margin-bottom:2px}')
parts.append('.ovfr{display:flex;flex-wrap:wrap;gap:4px}')
parts.append('.fb{padding:4px 12px;border-radius:16px;border:1px solid rgba(255,255,255,.04);background:rgba(255,255,255,.02);font-size:10.5px;cursor:pointer;transition:all .25s;font-weight:500;color:#999;letter-spacing:.2px}')
parts.append('.fb:hover{border-color:rgba(255,255,255,.12);background:rgba(255,255,255,.05);color:#ddd;transform:translateY(-1px)}.fb.off{opacity:.15;text-decoration:none;transform:scale(.95)}')
parts.append('.fbl{border-color:rgba(235,75,75,.15);color:var(--r1);font-weight:700;background:rgba(235,75,75,.04);font-size:10px}.fbl:hover{background:rgba(235,75,75,.1);color:#fff;border-color:var(--r1)}')
parts.append('.ovff{display:flex;align-items:center;justify-content:space-between;padding-top:4px;border-top:1px solid rgba(255,255,255,.03)}')
parts.append('.ovrc{font-size:11px;color:var(--fg2);font-weight:500}.ovg{padding:24px}')
parts.append('.ftr2{background:var(--bg2);border-top:1px solid rgba(255,255,255,.04);padding:28px 24px;text-align:center;position:relative;z-index:1}')
parts.append('.ftr2 p{color:#555;font-size:11px;max-width:400px;margin:0 auto;line-height:1.6}')

new_css = ''.join(parts)
new_block = "css = '''<style>" + new_css + "</style>'''"

new_content = content[:style_start] + new_block + content[style_end:]

with open('C:\\Users\\Student\\Desktop\\summer-school\\generate_html.py', 'w') as f:
    f.write(new_content)

print(f'CSS replaced! {len(new_css)} chars')
